# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd5420bd07ebb02bf42039a580cb089e429c1f21bfe6d2864b14eab6b14033f65e928d35d1fc10675c50dbb31664b8bc6f6eb391598f50670af59afd16019e6e

test:
  secret_key_base: a3c67223a1459c5038561a17413bffb6215f089f78f778d3f0b49ed367f84c16bb116ac48a0f2f1eb305282c64c4bb8f508b7ccfc0dfa83e80e0168cc2842fa6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
